version: '3.1'

services:
  categories_service:
    image: categories-service
    build: ./categories-service
    container_name: categories
    command: uvicorn app.main:app --reload --host 0.0.0.0 --port 8000
    volumes:
      - ./categories-service/:/app/
    ports:
      - 8001:8000
    secrets:
      - db_uri
    environment:
      - AUTH_SERVICE_URL=http://auth_service:8000/api/auth/basic
      - DATABASE_URI=/run/secrets/db_uri
    depends_on:
      - auth_service
      - db
    deploy:
      replicas: 3
      update_config:
        parallelism: 3
      restart_policy:
        condition: on-failure

  auth_service:
    image: auth-service
    build: ./auth-service
    container_name: auth
    command: uvicorn app.main:app --reload --host 0.0.0.0 --port 8000
    volumes:
      - ./auth-service/:/app/
    ports:
      - 8002:8000
    secrets:
      - login
      - password
    environment:
      - LOGIN=/run/secrets/login
      - PASSWORD=/run/secrets/password
    depends_on:
      - db
    deploy:
      replicas: 3
      update_config:
        parallelism: 3
      restart_policy:
        condition: on-failure

  db:
    image: postgres:12
    container_name: db
    secrets:
      - login
      - password
    environment:
      POSTGRES_DB: northwind
      POSTGRES_USER_FILE: /run/secrets/login
      POSTGRES_PASSWORD_FILE: /run/secrets/password
    volumes:
      - ./dbdata:/var/lib/postgresql/data
      - ./northwind.sql:/docker-entrypoint-initdb.d/northwind.sql
    deploy:
      placement:
        constraints: [node.role == manager]

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "8080:8080"
    volumes:
      - ./nginx_config.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - auth_service
      - categories_service
    deploy:
      placement:
        constraints: [node.role == manager]

secrets:
  db_uri:
    file: ./secrets/db_uri.txt
  login:
    file: ./secrets/login.txt
  password:
    file: ./secrets/password.txt
